---
# tasks file for fetch_network_backups

- name: Sync Pull from Remote Workers
  ansible.posix.synchronize:
    src: "{{ remote_config_directory }}"
    dest: "{{ local_config_directory }}"
    recursive: true
    times: true
    mode: pull
  delegate_to: "{{ awx_host }}"
  run_once: true
