---
# tasks file for fetch_network_backups

- name: Sync Pull from Remote Workers
  ansible.posix.synchronize:
    src: "{{ remote_config_directory }}"
    dest: "{{ local_config_directory }}"
    recursive: True
    times: True
  delegate_to: "{{ item }}"
  with_items: "{{ remote_worker_hostnames }}"
  run_once: True
