---
# tasks file for fetch_network_backups

- name: Sync Pull from Remote Workers
  ansible.posix.synchronize:
    # mode: push
    src: "{{ remote_config_directory }}"
    dest: rsync://{{ rsync_username }}@{{ awx_host }}/{{ local_config_directory }}
    recursive: True
    private_key: ~/.ssh/ansible_rsa
    set_remote_user: True
  delegate_to: "{{ inventory_hostname }}"
