---
# tasks file for fetch_network_backups

- name: Sync Pull from Remote Workers
  ansible.posix.synchronize:
    mode: push
    src: "{{ local_config_directory }}"
    dest: rsync://{{ inventory_host }}/{{ remote_config_directory }}
    recursive: True
